import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { DemandEntry } from '../../../shared/src/types';
import { api } from '../lib/api';
import { colors } from '../theme/theme';
type Props = { initialName?: string; source?: 'manual' | 'missing-app-discovery' };
export default function RequestScreen({ initialName = '', source = 'manual' }: Props){
 const [appName,setAppName]=useState(initialName);const[note,setNote]=useState('');const[demand,setDemand]=useState<DemandEntry[]>([]);const[opportunities,setOpportunities]=useState<DemandEntry[]>([]);const[demandTotal,setDemandTotal]=useState(0);const[recentTotal,setRecentTotal]=useState(0);const[last7Total,setLast7Total]=useState(0);const[status,setStatus]=useState('');const[loading,setLoading]=useState(false);
 const loadDemand=()=>api.demand(30).then(result=>{setDemand(result.topDemand);setOpportunities(result.topOpportunities);setDemandTotal(result.totalRequests);setRecentTotal(result.recentRequests);setLast7Total(result.last7DaysRequests);}).catch(()=>{setDemand([]);setDemandTotal(0);});useEffect(()=>{loadDemand();},[]);
 useEffect(()=>{if(initialName) setAppName(initialName);},[initialName]);
 const submit=async()=>{if(appName.trim().length<2){setStatus('Enter an app name first.');return;}setLoading(true);setStatus('');try{const result=await api.createRequest(appName.trim(),note.trim(),source);setAppName('');setNote('');setStatus(result.duplicateOf ? `Demand already exists. ${result.appName} now has ${result.demandCount || 1} requests. Your request was added to the signal.` : `Request recorded. ${result.appName} now has the first demand signal.`);await loadDemand();}catch(e){setStatus(e instanceof Error?e.message:'Could not submit request.');}finally{setLoading(false);}};
 return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.kicker}>APP REQUEST NETWORK</Text><Text style={styles.title}>What is missing?</Text><Text style={styles.sub}>Turn viewer demand into a signal developers can act on.</Text>{source === 'missing-app-discovery' ? <View style={styles.context}><Text style={styles.contextLabel}>MISSING APP DETECTED</Text><Text style={styles.contextText}>This request was opened from ARCHANGEL App Discovery because the app was not found in the current catalog.</Text></View> : null}
 <TextInput value={appName} onChangeText={setAppName} placeholder="App name" placeholderTextColor="#888888" style={styles.input}/><TextInput value={note} onChangeText={setNote} placeholder="Why do you want it? (optional)" placeholderTextColor="#888888" style={[styles.input,styles.note]} multiline/>
 <Pressable onPress={submit} style={({focused})=>[styles.button,focused&&styles.buttonFocused]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>REQUEST APP</Text>}</Pressable>{status?<Text style={styles.status}>{status}</Text>:null}
 <Text style={styles.section}>DEVELOPER OPPORTUNITY • 30 DAYS</Text><Text style={styles.total}>Demand signals ranked by recency, momentum and discovery intent.</Text>{opportunities.slice(0,5).map((item,i)=><View key={`opp-${item.normalizedName || item.appName}-${i}`} style={styles.opportunity}><View style={styles.oppMain}><Text style={styles.demandName}>{item.appName}</Text><Text style={styles.demandMeta}>{item.opportunityReasons?.slice(0,2).join(" • ") || "Emerging demand signal"}</Text></View><View style={styles.oppScore}><Text style={styles.oppNumber}>{item.opportunityScore || 0}</Text><Text style={styles.scoreLabel}>OPPORTUNITY</Text><Text style={item.opportunity === "high" ? styles.trendDown : styles.trend}>{(item.opportunity || "emerging").toUpperCase()}</Text></View></View>)}{opportunities.length===0?<Text style={styles.empty}>No strong opportunity signals yet.</Text>:null}<Text style={styles.section}>DEMAND INTELLIGENCE • 30 DAYS</Text><Text style={styles.total}>{demandTotal} total • {recentTotal} last 30d • {last7Total} last 7d</Text>{demand.slice(0,8).map((item,i)=><View key={`${item.normalizedName || item.appName}-${i}`} style={styles.demand}><View style={styles.demandMain}><Text style={styles.demandName}>{item.appName}</Text><Text style={styles.demandMeta}>{item.discoveryRequests || 0} discovery • {item.manualRequests || 0} manual • {item.last7Days || 0} last 7d</Text></View><View style={styles.score}><Text style={styles.count}>{item.demandScore || item.count}</Text><Text style={styles.scoreLabel}>SCORE</Text><Text style={item.trend === 'rising' ? styles.trendUp : item.trend === 'falling' ? styles.trendDown : styles.trend}>{item.trend === 'rising' ? '↑' : item.trend === 'falling' ? '↓' : '→'} {Math.abs(item.trendPercent || 0)}%</Text></View><View><Text style={styles.count}>{item.count}</Text><Text style={styles.requests}>requests</Text></View></View>)}{demand.length===0?<Text style={styles.empty}>No requests yet. Be the first signal.</Text>:null}</ScrollView>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:48,paddingHorizontal:64,paddingBottom:70},kicker:{color:colors.red,fontSize:13,letterSpacing:2,fontWeight:'700'},title:{color:colors.text,fontSize:42,fontWeight:'900',marginTop:6},sub:{color:colors.muted,fontSize:19,marginBottom:18},context:{width:700,backgroundColor:colors.paleRed,borderWidth:1,borderColor:colors.red,borderRadius:10,padding:14,marginBottom:16},contextLabel:{color:colors.red,fontSize:10,fontWeight:'900',letterSpacing:1.5},contextText:{color:colors.text,fontSize:14,lineHeight:20,marginTop:5},input:{width:700,height:58,borderRadius:10,backgroundColor:colors.panel,borderWidth:2,borderColor:colors.line,color:colors.text,fontSize:20,paddingHorizontal:18,marginBottom:12},note:{height:90,paddingTop:15,textAlignVertical:'top'},button:{alignSelf:'flex-start',backgroundColor:colors.red,paddingHorizontal:28,paddingVertical:15,borderRadius:8,minWidth:190,alignItems:'center'},buttonFocused:{backgroundColor:colors.text},buttonText:{color:'#fff',fontSize:15,fontWeight:'900',letterSpacing:1},status:{color:colors.success,fontSize:16,marginTop:14},section:{color:colors.red,fontSize:13,letterSpacing:2,fontWeight:'700',marginTop:34,marginBottom:4},total:{color:colors.muted,fontSize:14,marginBottom:12},demand:{width:700,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,padding:16,borderRadius:10,marginBottom:9,flexDirection:'row',alignItems:'center'},demandMain:{flex:1},demandName:{color:colors.text,fontSize:19,fontWeight:'800'},demandMeta:{color:colors.muted,fontSize:11,marginTop:3},opportunity:{width:700,backgroundColor:colors.paleRed,borderWidth:1,borderColor:colors.red,padding:16,borderRadius:10,marginBottom:9,flexDirection:'row',alignItems:'center'},oppMain:{flex:1},oppScore:{alignItems:'center',marginLeft:18},oppNumber:{color:colors.red,fontSize:28,fontWeight:'900'},score:{alignItems:'center',marginRight:18},scoreLabel:{color:colors.muted,fontSize:9,fontWeight:'800',letterSpacing:1},trend:{color:colors.muted,fontSize:10,fontWeight:'800',marginTop:3},trendUp:{color:colors.success,fontSize:10,fontWeight:'900',marginTop:3},trendDown:{color:colors.red,fontSize:10,fontWeight:'900',marginTop:3},count:{color:colors.red,fontSize:22,fontWeight:'900'},requests:{color:colors.muted,fontSize:13,marginLeft:7},empty:{color:colors.muted,fontSize:17}});
